export default {
  USER_AUTH: 'USER_AUTH',
  USER_AUTH_START: 'USER_AUTH_START',
  USER_AUTH_COMPLETE: 'USER_AUTH_COMPLETE',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_COMPLETE: 'USER_LOGOUT_COMPLETE'
};